import streamlit as st
from pathlib import Path
import pandas as pd
from nevergrad_code import run_runs
from pyvrp import read, read_solution
from pyvrp.stop import MaxIterations
from pyvrp.plotting import plot_result
from pyvrp import solve 
import matplotlib.pyplot as plt

# ----------------------------
# Streamlit UI
# ----------------------------
st.set_page_config(page_title="Solver with Nevergrad", page_icon="🚚")
st.title(":material/auto_awesome: Vehicle routing problem solver with Nevergrad")

st.warning("If the page fails to load properly, try refreshing it.")
st.info("Choose a CVRP test problem and an initial solution strategy. The solver uses evolutionary algorithms (NGOpt, DE, OnePlusOne) to optimize routes and cost.")

with st.expander("More about this solver"):
    st.write("This algorithm is based on Nevergrad, a Python library for derivative-free optimization developed by Facebook Research. " \
         "The implementation here focuses on solving the Capacitated Vehicle Routing Problem (CVRP) using seeded and unseeded optimization strategies. " \
        "The seeded mode starts from a heuristic solution (Christofides or PATH_CHEAPEST_ARC) generated by OR-Tools on the previous page. " \
        "The unseeded optimization starts from scratch without any initial solution. " \
        "The user can set the number of independent runs and the budget (number of evaluations) for the optimization process. " \
        "Right now three algorithms are supported: NGOpt, OnePlusOne, and DE (Differential Evolution).")

# --- Configure test problems ---
BASE_DIR = Path(__file__).parent
TEST_DIR = BASE_DIR / "CVRP_TEST"

TEST_PROBLEMS = {
    "X-n101-k25": TEST_DIR / "X-n101-k25.vrp",
    "X-n219-k73": TEST_DIR / "X-n219-k73.vrp",
    "X-n322-k28": TEST_DIR / "X-n322-k28.vrp",
}

problem_name = st.selectbox("Select test problem:", list(TEST_PROBLEMS.keys()))
vrp_path = TEST_PROBLEMS[problem_name]

# --- Choose initial solution ---
initializer = st.radio("Choose initial solution:", ["CHRISTOFIDES", "PATH_CHEAPEST_ARC"])
seed_prefix = "Christofides" if initializer == "CHRISTOFIDES" else "PATH_CHEAPEST"
seed_path = TEST_DIR / f"{seed_prefix}_{problem_name}.sol"

if seed_path.exists():
    st.success(f"Using seed solution: {seed_path.name}")
else:
    st.warning(f"Seed solution '{seed_path.name}' not found — running unseeded only.")
    seed_path = None

# --- Parameters ---
ALGOS = ["NGOpt", "OnePlusOne", "DE"]
RUNS = st.number_input("Number of independent runs", value=5, min_value=1, step=1)
BUDGET = st.number_input("Budget (number of evaluations)", value=500, min_value=1, step=100)

# --- Run button ---
if st.button("Run Optimization"):

    if not vrp_path.exists():
        st.error(f"VRP file not found: {vrp_path}")
    else:
        st.info(f"Running Nevergrad optimization for problem: {problem_name}")

        # Run the Nevergrad experiments
        rows = run_runs(
            str(vrp_path),
            algos=ALGOS,
            budget=BUDGET,
            runs=RUNS,
            seed_solutions=str(seed_path) if seed_path else None
        )

        # Convert to DataFrame
        df = pd.DataFrame(rows)

        # Compute baseline (per-run seeded solution cost)
        baseline_cost = df[df["mode"]=="seeded"]["cost"].min()

        # Aggregate summary
        agg_list = []
        for (algo, mode), group in df.groupby(["algo","mode"]):
            mean_cost = group["cost"].mean()
            best_cost = group["cost"].min()
            mean_routes = group["routes"].mean()
            mean_rt = group["runtime_sec"].mean()
            n_runs = len(group)
            gap = ((mean_cost - baseline_cost)/baseline_cost*100) if baseline_cost else None

            agg_list.append({
                "Algo": algo,
                "Mode": mode,
                "Mean Cost": round(mean_cost,1),
                "Best Cost": best_cost,
                "Mean Routes": round(mean_routes,2),
                "Mean Rt(s)": round(mean_rt,2),
                "#Runs": n_runs,
                "Gap% vs baseline": round(gap,2) if gap is not None else None
            })

        df_agg = pd.DataFrame(agg_list)
        st.subheader("Aggregate Summary")
        st.dataframe(df_agg)

    st.subheader("Example VRP Solution Visualization")

    try:
        INSTANCE = read(str(vrp_path), round_func="round")

        bks_path = TEST_DIR / f"{problem_name}.sol"

        # Solve a short run just for visualization
        result = solve(
            INSTANCE,
            stop=MaxIterations(2000),
            seed=25,
            display=False,
        )

        # Plot on Streamlit
        fig = plt.figure(figsize=(12, 7))
        plot_result(result, INSTANCE, fig)
        fig.tight_layout()
        st.pyplot(fig)

    except Exception as e:
        st.error(f"Unable to render plot: {e}")